### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by namirsab** [namirsab/project-mgmt-example#1]
## Value Statement

As a user of "Super Courses"
I want to have a responsive layout
so I can access the app with any device

## Description
![Basic Layout](https://user-images.githubusercontent.com/6980777/115355592-19e00480-a1bb-11eb-9a15-c472a551b576.png)
> No need for description here

## Acceptance Criteria
* The app should have an always visibile header containing the app name and logo:
* The app should have an always visible footer. It will be used for navigating between pages
* The app should be responsive

## Tasks
* [ ] Setup React, React Router DOM
* [ ] Setup component for Global Layout
* [ ] Define primary colors in the `:root` selector
* [ ] Write CSS for the Global Layout component
