### ISSUE TITLE
View Courses Page

### ISSUE THREAD

**Issue by namirsab** [namirsab/project-mgmt-example#2]
## Value Statement
As a user of "Super Courses"
I want to see a list with all available courses
so that I can know which courses are available and navigate to them

## Description
In the home page, show the available courses. Courses have a clickable area that will be used to navigate to a course detail page:

![Course Page(1)](https://user-images.githubusercontent.com/6980777/115365657-e30eec00-a1c4-11eb-8d55-db472482fe31.png)

## Acceptance Criteria
* The page should render a list of courses coming from the API
* Each course in the list should show:
   * An index of the course (1, 2, 3)
   * The course name
   * The course location
   * A button that would be used to navigate to the course detail page
* The navigation at the bottom should be highligting the "Courses" button, indicating we are in the courses page.

## Tasks
* [ ] Create react component for the <CourseListItem />, with styles in a separate file `CourseListItem.css`
   * [ ] It receives the data of a course as props
   * [ ] It should have a prop `onClick` to handle when the button of the course was clicked
* [ ] Create react component for the <CourseList /> with styles in a separate file `CourseList.css`
    * [ ] This component should be responsible of fetching the data from the API and render the list of `<CourseListItem />`s
## Complexity
Medium
