### ISSUE TITLE
Create Course Page

### ISSUE THREAD

**Issue by namirsab** [namirsab/project-mgmt-example#3]
## Value Statement
As a user of "Super Courses"
I want to be able to create new courses
so I can define them and later add students to them

## Description
![Create Course Page](https://user-images.githubusercontent.com/6980777/115373771-7861ae80-a1cc-11eb-8f50-f941af0bb1a6.png)

## Acceptance Criteria
* In the View Courses Pages, the user should have a button to allow them to go to the "Create Course Page"
* In the Create Course Page, the user should be able to add a title and a location for the course in a form.
* Name and Location cannot be empty
* If a course with the same name already exists, the the app shows the user an error when the user submits the form
* When the course is successfully created, the user receives a message and gets redirected back to the View Courses page

## Tasks
* [ ] Add button in the View Courses Page. The button should move the user to a new route using React Router.
* [ ] Create new component for the <CreateCourse />` page
* [ ] Create a `<CreateCourseForm />` component
* [ ] Make the `<CreateCourseForm />`component communicate with the API to create a new course when the form is submitted.
* [ ] When the course is submitted, use `history` to move the user back to the View Courses page

## Complexity

Large
